// In-memory database - data diambil dari dummy data Flutter app
// Di production, ganti dengan database sungguhan (PostgreSQL/MongoDB)

const { v4: uuidv4 } = require('uuid');

const db = {
  users: [
    {
      id: 'user-1',
      name: 'Admin Sasacation',
      email: 'admin@sasacation.com',
      password: '$2a$10$jcmSboxQkPdpL9R.vfEQV.37pmNMfmd7OhjImf7Itl60f4H79CgW2', // admin123
      role: 'admin',
      avatar: null,
      provider: 'email',
      createdAt: new Date('2024-01-01'),
    },
    {
      id: 'user-2',
      name: 'Budi Santoso',
      email: 'budi@example.com',
      password: '$2a$10$jcmSboxQkPdpL9R.vfEQV.37pmNMfmd7OhjImf7Itl60f4H79CgW2', // admin123
      role: 'user',
      avatar: null,
      provider: 'email',
      createdAt: new Date('2024-02-01'),
    },
  ],

  hotels: [
    {
      id: '1',
      name: 'Qunci Villas',
      location: 'Mangsit Beach',
      address: 'Jl. Raya Senggigi Km 8, Mangsit, Lombok Barat',
      price: 179,
      rating: 4.8,
      reviewCount: 312,
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d',
      images: [
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d',
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4',
        'https://images.unsplash.com/photo-1540541338287-41700207dee6',
      ],
      description: 'Qunci Villas adalah resort bintang 5 yang terletak langsung di tepi pantai Mangsit yang tenang. Dengan 56 villa pribadi yang dikelilingi taman tropis yang rimbun, setiap villa memiliki kolam renang pribadi dan pemandangan langsung ke Selat Lombok.',
      amenities: ['Private Pool', 'Beach Access', 'Spa', 'Restaurant', 'Bar', 'WiFi', 'Airport Transfer'],
      category: 'Hotels',
      type: 'hotel',
      featured: true,
      available: true,
    },
    {
      id: '2',
      name: 'Oberoi Beach Resort',
      location: 'Tanjung',
      address: 'Medana Beach, Tanjung, Lombok Utara',
      price: 341,
      rating: 4.9,
      reviewCount: 256,
      image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6',
      images: [
        'https://images.unsplash.com/photo-1540541338287-41700207dee6',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d',
      ],
      description: 'Oberoi Beach Resort Lombok merupakan salah satu resort paling mewah di Lombok. Terletak di pantai Medana yang terpencil, resort ini menawarkan pengalaman menginap eksklusif dengan pemandangan laut yang luar biasa.',
      amenities: ['Private Beach', 'Infinity Pool', 'Spa', 'Dive Center', 'Restaurant', 'WiFi', 'Butler Service'],
      category: 'Hotels',
      type: 'hotel',
      featured: true,
      available: true,
    },
    {
      id: '7',
      name: 'Katamaran Resort',
      location: 'Senggigi',
      address: 'Jl. Raya Senggigi, Lombok Barat',
      price: 224,
      rating: 4.6,
      reviewCount: 189,
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4',
      images: [
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4',
      ],
      description: 'Katamaran Resort & Spa adalah hotel bintang 4 yang berlokasi strategis di kawasan Senggigi, pusat pariwisata Lombok. Dengan pemandangan langsung ke Selat Lombok dan Gunung Agung Bali.',
      amenities: ['Pool', 'Spa', 'Restaurant', 'Bar', 'WiFi', 'Water Sports'],
      category: 'Hotels',
      type: 'hotel',
      featured: true,
      available: true,
    },
    {
      id: '8',
      name: 'Puri Mas Boutique Resort',
      location: 'Mangsit',
      address: 'Jl. Raya Senggigi Km 7, Mangsit',
      price: 145,
      rating: 4.5,
      reviewCount: 143,
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
      images: [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945',
      ],
      description: 'Puri Mas Boutique Resort adalah resort butik yang nyaman dengan nuansa Sasak yang kental. Cocok untuk wisatawan yang ingin merasakan budaya lokal Lombok.',
      amenities: ['Pool', 'Restaurant', 'Cultural Activities', 'WiFi', 'Garden'],
      category: 'Hotels',
      type: 'hotel',
      featured: false,
      available: true,
    },
  ],

  destinations: [
    {
      id: '3',
      name: 'Mount Rinjani',
      location: 'North Lombok',
      address: 'Taman Nasional Gunung Rinjani, Lombok Utara',
      price: 0,
      rating: 4.9,
      reviewCount: 1205,
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
      images: [
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
      ],
      description: 'Gunung Rinjani adalah gunung berapi aktif tertinggi kedua di Indonesia dengan ketinggian 3.726 mdpl. Pendakian ke puncaknya menawarkan pemandangan yang spektakuler dengan danau kawah Segara Anak yang indah.',
      category: 'Destinations',
      type: 'destination',
      subCategory: 'Adventure',
    },
    {
      id: '4',
      name: 'Gili Trawangan',
      location: 'Gili Islands',
      address: 'Kepulauan Gili, Lombok Utara',
      price: 0,
      rating: 4.8,
      reviewCount: 2341,
      image: 'https://images.unsplash.com/photo-1512641406448-6574e7773702',
      images: [
        'https://images.unsplash.com/photo-1512641406448-6574e7773702',
      ],
      description: 'Gili Trawangan adalah pulau terbesar dari tiga Gili bersaudara. Dikenal dengan pantainya yang putih, air yang jernih, dan kehidupan bawah lautnya yang kaya. Tidak ada kendaraan bermotor di pulau ini.',
      category: 'Destinations',
      type: 'destination',
      subCategory: 'Islands',
    },
    {
      id: '9',
      name: 'Pantai Pink',
      location: 'East Lombok',
      address: 'Desa Sekaroh, Jerowaru, Lombok Timur',
      price: 0,
      rating: 4.7,
      reviewCount: 876,
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      images: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
      ],
      description: 'Pantai Pink atau Tangsi adalah pantai unik dengan pasir berwarna pink kemerahan. Warna pink berasal dari pecahan karang merah yang bercampur dengan pasir putih.',
      category: 'Destinations',
      type: 'destination',
      subCategory: 'Beaches',
    },
    {
      id: '10',
      name: 'Desa Sade',
      location: 'Central Lombok',
      address: 'Desa Sade, Rembitan, Pujut, Lombok Tengah',
      price: 0,
      rating: 4.5,
      reviewCount: 654,
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
      images: [
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
      ],
      description: 'Desa Sade adalah desa tradisional suku Sasak yang masih mempertahankan adat istiadat dan arsitektur tradisional. Di sini kamu bisa melihat rumah adat Sasak dan tenun khas Lombok.',
      category: 'Destinations',
      type: 'destination',
      subCategory: 'Culture',
    },
  ],

  restaurants: [
    {
      id: '5',
      name: 'Taliwang Khas Pak Udin',
      location: 'Mataram',
      address: 'Jl. Selaparang No. 5, Mataram',
      price: 15,
      rating: 4.6,
      reviewCount: 432,
      image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
      images: [
        'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
      ],
      description: 'Warung makan legendaris yang menyajikan Ayam Taliwang, makanan khas Lombok. Dengan bumbu rempah yang otentik dan cita rasa yang khas, tempat ini wajib dikunjungi.',
      cuisine: 'Sasak Traditional',
      openHours: '10:00 - 22:00',
      category: 'Culinary',
      type: 'restaurant',
    },
    {
      id: '6',
      name: 'Sate Rembiga Bu Ririn',
      location: 'Mataram',
      address: 'Jl. Rembiga, Mataram',
      price: 12,
      rating: 4.7,
      reviewCount: 567,
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
      images: [
        'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
      ],
      description: 'Sate Rembiga adalah sate khas Lombok yang menggunakan daging sapi dengan bumbu yang kaya rempah. Bu Ririn adalah salah satu penjual sate rembiga paling terkenal di Mataram.',
      cuisine: 'Sasak Traditional',
      openHours: '11:00 - 21:00',
      category: 'Culinary',
      type: 'restaurant',
    },
    {
      id: '11',
      name: 'Warung Menega Cafe',
      location: 'Senggigi',
      address: 'Jl. Raya Senggigi, Senggigi',
      price: 25,
      rating: 4.4,
      reviewCount: 234,
      image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
      images: [
        'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
      ],
      description: 'Warung Menega menawarkan seafood segar dengan pemandangan laut Senggigi. Menu andalan adalah ikan bakar dan lobster yang dimasak dengan bumbu khas Sasak.',
      cuisine: 'Seafood',
      openHours: '12:00 - 23:00',
      category: 'Culinary',
      type: 'restaurant',
    },
  ],

  bookings: [],

  categories: [
    { id: 'beaches', label: 'Beaches', icon: 'beach_access', description: 'Beautiful beaches in Lombok' },
    { id: 'hotels', label: 'Hotels', icon: 'hotel', description: 'Luxury resorts & villas' },
    { id: 'culinary', label: 'Culinary', icon: 'restaurant', description: 'Local delicacies' },
    { id: 'islands', label: 'Islands', icon: 'directions_boat', description: 'Gili Islands paradise' },
    { id: 'adventure', label: 'Adventure', icon: 'hiking', description: 'Mount Rinjani trek' },
    { id: 'culture', label: 'Culture', icon: 'museum', description: 'Sasak tradition' },
  ],

  // Checkout & payment — diinisialisasi di sini agar tidak ada race condition
  checkoutSessions: [],
  payments: [],
};

module.exports = db;
